### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by sswitlik** [borowskimarcin/shortcuts-stats#2]
Add possibility to export data to csv file, or at least to copy all data to clipboard

**Comment by borowskimarcin** [comment]
I think this feature could be added. Just need to know how you would like to use that file, what is the purpose? Would you like to have an export/import functionality or just for some personal use?

**Comment by sswitlik** [comment]
Thank you for your answer :) 
In our company we want to compare how different developers use shortcuts and by that learn from each other useful tips. Plugins like Key Promotor do not detect all actions (for example Ctrl+Alt+M = Extract Method) so I find this plugin a perfect tool to learn.

Having this data exported will allow us to make some comparing statistics and possibility for developers to see what the others use.

If you have any more questions I will gladly answer them.

**Comment by borowskimarcin** [comment]
Ok, will create such feature to save to csv format, e.g.:
```
name,description,count
⌘E,Recent Files,1431
⇥,Tab,1397
⌘B,Go to Declaration or Usages,1049
⌃R,Run,985
⌘⌫,Delete Line,946
F8,Step Over,920
⌥⏎,N/A - unknown shortcut description,858
⌥→,Move Caret to Next Word,754
⇧⌘→,Move Caret to Line End with Selection,591
⌘\,Manage Projects...,543
⌘D,Show Diff,497
⇞,Page Up,474
⌥←,Move Caret to Previous Word,472
⇧⌘←,Move Caret to Line Start with Selection,462
⌘N,New...,450
```

**Comment by borowskimarcin** [comment]
`JetBrains is reviewing this update. Please expect it to be approved within two business days of the upload.` Changes should be available within two working days.

**Comment by sswitlik** [comment]
I've just tested it. Works exactly how I wanted. Thank you a lot.
